name: Code Style

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest
    name: Code Style
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Check Style
        uses: actionsx/prettier@v2
        with:
          args: -c .
